languageCode = "th-TH"
title = "แกงบูดฟันตาซี 's Site"
baseurl = "https://gbfuntasy.github.io/"
theme = "ghostwriter"
canonifyurls = true
author = "GBFuntasy"
copyright = "GBFuntasy"

[Author]
    name = "GBFuntasy"
    profile = "https://facebook.com/GBFuntasy"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[Params]
  intro = true
  description = "แกงหม้อนี้ไม่บูด"
  opengraph = true
  github = "https://github.com/gbfuntasy"
  facebook = "https://facebook.com/gbfuntasy"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
weight = 4
